# Generated by Django 2.0.2 on 2018-03-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=246)),
                ('lastName', models.CharField(max_length=246)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
