# Generated by Django 2.0.3 on 2018-03-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='porfolio_site',
            new_name='portfolio_site',
        ),
    ]
